services:
  backend:
    build: ./backend
    image: plantai-backend
    ports:
      - "8000:8000"
    environment:
      PLANTNET_API_KEY: "${PLANTNET_API_KEY}"
      GEMINI_API_KEY: "${GEMINI_API_KEY}"
#      DB_HOST: "db"
#      DB_PORT: 5432
#      DB_USER: "${DB_USER}"
#      DB_PASS: "${DB_PASS}"
#      DB_NAME: "${DB_NAME}"
#  db:
#    image: postgres:18
#    environment:
#      POSTGRES_USER: "${DB_USER}"
#      POSTGRES_PASSWORD: "${DB_PASS}"
#      POSTGRES_DB: "${DB_NAME}"
#    volumes:
